import { LineEdit , Button, GridBox} from "std-widgets.slint";

export component NumberField inherits Rectangle {
    in property <string> title: "Default title here";
    in-out property <string> text: "";
    in property <string> placeholder_text: "Start typing here...";
    in property <string> prefix_text: "";
    in property <string> suffix_text: "";
    in property <string> tooltip_text: "";
    //in property <int> title_font_size: 16;
    //in property <int> entry_font_size: 14;
    preferred-width: 100%;
    min-height: 58px;
    min-width: 50px;
    border-color: white;
    border-radius: 10px;
    border-width: 1px;
    background: black;
    horizontal-stretch: 0;

    // Title
    Text {
        x: 8px;
        y: 4px;

        font-size: 14px;
        text: title;
    }
    // Text Entry field
    LineEdit {
        x: 35px;
        y: 24px;
        height: 24px;
        width: root.width - 40px;
        
        font-size: 14px;
        placeholder-text: placeholder_text;
    }
    // Prefix
    Text {
        x: 2px;
        y: 28px;
        min-width: 30px;
        font-size: 14px;
        text: prefix-text;
        horizontal-alignment: right;
    }

    // Suffix
    Text {
        x: root.width - 10px - self.width;
        y: 28px;
        min-width: 30px;
        font-size: 14px;
        text: suffix-text;
        horizontal-alignment: right;
    }
    // Question mark
    Rectangle {
        x: parent.width - 20px;
        y: 4px;
        width: 16px;
        height: 16px;
        border-radius: 5px;
        //background: blue;

        Text {
            text: "?";
            color: white;
            font-size: 14px;
        }
    }
}

export component SpinBoxLabel inherits HorizontalLayout {
    spacing: 3px;
    padding: 6px;
    //alignment: space-around;

    in property <string> name;
    in property <float> value;
    in property <string> label;

    Text {
        text: name + ":";
        color: lightsteelblue;
        font-size: 14px;
        horizontal-alignment: left;
        vertical-alignment: center;
    }

    Text {
        text: label;
        color: white;
        font-size: 16px;
        horizontal-alignment: right;
        vertical-alignment: center;
    }

    LineEdit {
        font-size: 14px;
        width: parent.width*0.5;
        //height: parent.height;
        placeholder-text: "Enter here " + value;
    }
}

export component MainWindow inherits Window {
    title: "Retirement Calculator";
    //width: 800px;
    //height: 600px;
    min-width: 800px;
    min-height: 500px;
    VerticalLayout {
        GridBox { 
            spacing: 10px;
            padding: 10px;
            Row {
                NumberField {
                    title: "Current Age";
                    placeholder-text: 36;
                    suffix-text: "years";
                }
                NumberField {
                    title: "Age of Death";
                    placeholder-text: 85;
                    suffix-text: "years";
                }
            }
            Row {
                NumberField {
                    title: "Retirement Age";
                    placeholder-text: 59.5;
                    suffix-text: "years";
                }
                NumberField {
                    title: "Social Security Age";
                    placeholder-text: 67;
                    suffix-text: "years";
                }
            }
            Row {
                NumberField {
                    title: "Starting Balance";
                    placeholder-text: 20000;
                    prefix-text: "$";
                }
                NumberField {
                    title: "Social Security Monthly Income";
                    placeholder-text: 20000;
                    prefix-text: "$";
                }
                NumberField {
                    title: "Montly Contribution";
                    placeholder-text: 1000;
                    prefix-text: "$";
                }
            }
            Row {
                
            }
            Row {
                NumberField {
                    title: "Investment yield before retirement";
                    placeholder-text: "7.0";
                    suffix-text: "%";
                }
                NumberField {
                    title: "Investment yield after retirement";
                    placeholder-text: "7.0";
                    suffix-text: "%";
                }
                NumberField {
                    title: "Inflation rate";
                    placeholder-text: "3.0";
                    suffix-text: "%";
                }
            }
            Row {
                NumberField {
                    title: "Annual income needed post-retirement";
                    placeholder-text: "7.0";
                    suffix-text: "%";
                }

                NumberField {
                    title: "Annual income post-retirement decay";
                    placeholder-text: "10.0";
                    suffix-text: "%";
                }
            }
        }

        Button { 
            text: "Calculate";
        }
        Rectangle {
            //width: parent.width;
            height: 300px;
            background: white;
            Text {
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Line Graph will go here";
                font-size: 20px;
                color: black;
            }
        }
        
        Button { 
            text: "Export";
        }
    }
}
